version: 2.1

jobs:
  deploy:
    docker:
      - image: hashicorp/terraform:latest
    environment:
      AWS_DEFAULT_REGION: "us-east-1"
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: |
            cd Terraform
            terraform init
      - run:
          name: Terraform Plan
          command: |
            cd Terraform
            terraform plan
      - run:
          name: Terraform Apply
          command: |
            cd Terraform
            terraform apply --auto-approve

  destroy:
    docker:
      - image: hashicorp/terraform:latest
    environment:
      AWS_DEFAULT_REGION: "us-east-1"
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: |
            cd Terraform
            terraform init
      - run:
          name: Terraform Destroy
          command: |
            cd Terraform
            terraform destroy --auto-approve

workflows:
  deploy-infrastructure:
    jobs:
      - deploy:
          filters:
            branches:
              only: main

  destroy-infrastructure:
    jobs:
      - destroy:
          filters:
            branches:
              only: destroy
